### ISSUE TITLE
[FEAT]  The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by klepiz** [hashicorp/vault-action#390] opened 2022-10-26 15:19 UTC
Currently when I use this action, Im getting this warning

```
Run hashicorp/vault-action@v2.4.0
  
Get Vault Secrets
Token Info
  
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```
Is it going to be a new release for this action with this fix/refactor?

**Comment by tvoran** [comment] 2022-10-26 18:47
Thanks, but this is a duplicate of #384

**Closed by tvoran** 2022-10-26 18:47 UTC
Labels: enhancement
