### ISSUE TITLE
[BUG] JSON.Stringify adds quotes

### ISSUE THREAD

**Issue by dirtycajunrice** [hashicorp/vault-action#88] opened 2020-07-17 23:45 UTC
**Describe the bug**
Output of a kv pair has quotes around them

**To Reproduce**
echo a kv value

**Expected behavior**
To get exactly what i put into the vault as a value

**Additional context**
This requires a workaround of echo `${DOCKERHUB_TOKEN//\"}` vs just manipulating and adding quotes as needed.

Edit: Side-Note ~ Heyo fellow austinite!

**Comment by RichiCoder1** [comment] 2020-07-18 00:11
Howdy Austinite!

That's odd. I actually added a smidge of logic to string out quotes: https://github.com/RichiCoder1/vault-action/blob/master/src/secrets.js#L67

I wonder if it's somehow getting double quoted? Do you have a specific reproduction?

**Comment by DirtyCajunRice** [comment] 2020-07-18 01:20
Just 10 attempts to docker login with creds that failed until i did the bash var substitution above. if i -format=json the kv pair in vault they are not quoted on their own; only the json-based quotes. Short of writing an action in an empty repo that echos i dont know the “easy” way to repro. 
My workflow saves them to a var as stated in the example docs and the references them directly in the next step via the echo ${VAR} syntax. Nothing fancy

**Comment by RichiCoder1** [comment] 2020-07-20 00:39
Sorry for the delay. I'll see if I can reproduce. Might be something simple

**Comment by imthaghost** [comment] 2022-03-16 21:32
Hey @dirtycajunrice is this still an issue you are experiencing? I am working on trying to reproduce your issue and couldn't really find the example of where the output of the `kv pair` has quotes.

**Comment by imthaghost** [comment] 2022-03-29 07:24
Hey @dirtycajunrice since we weren't able to replicate the issue we will be closing the issue. If you find this is a problem you are still experiencing feel free to reopen the issue and we can discuss more on replicating the issue you are coming across.

**Closed by imthaghost** 2022-03-29 07:24 UTC
Labels: bug
